Cloud bastion
Otus-DevOps-2021-11/feenord_infra pull request #2
Opened 2021-12-20 13:44 UTC by feenord

ДЗ по Знакомство с облачной
инфраструкт фраструктурой.
Yandex.Cloud

2021-12-20 15:14 UTC, mrgreyves requested changes
Здравствуйте!
У вас нет тестов
Видимо они не были добавлены еще в предыдущем дз, нужно это поправить =)

2021-12-20 15:20 UTC, feenord commented
Не понимаю честно говоря о чем идет речь. Я сегодня сдал и прошлую жз по
гиту и дз по yandex.cloud

пн, 20 дек. 2021 г. в 18:14, Vladimir Drozdetskiy ***@***.***
>:

> ***@***.**** requested changes on this pull request.
>
> Здравствуйте!
> У вас нет тестов
> Видимо они не были добавлены еще в предыдущем дз, нужно это поправить =)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2021-11/feenord_infra/pull/2#pullrequestreview-836504895>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW5AUAGGXQMZEPSLG7PHN53UR5B5HANCNFSM5KNXSPOQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-25 07:03 UTC, feenord reviewed
1

2022-02-09 12:07 UTC, mrgreyves requested changes
Здравствуйте!
<img width="870" alt="image" src="https://user-images.githubusercontent.com/34331259/153197860-7d64d951-a967-466e-b3eb-084ee7f38b4b.png">
1. У вас не добавлены тесты (добавлен Workflow для простановки проверяющего)
2. Файл который должен был быть протестирован в предыдущем дз в ошибками (оставил отдельную пометку)

2022-02-09 12:07 UTC, mrgreyves commented on test.ry
> +import unittest
Имя не правильное
Тесты тоже не исправны =(

2022-02-24 15:36 UTC, mrgreyves approved these changes
Здравствуйте!)
Отдельно с вами обсудили детали выполнения данного дз
Апрув =)

2022-02-24 15:36 UTC, mrgreyves commented on README.md
> +# bastion_IP = 51.250.8.61
Убрать решетку надо =)

2022-02-24 15:36 UTC, mrgreyves approved these changes
Здравствуйте!)
Отдельно с вами обсудили детали выполнения данного дз
Апрув =)

2022-02-24 15:36 UTC, mrgreyves approved these changes
Здравствуйте!)
Отдельно с вами обсудили детали выполнения данного дз
Апрув =)

2022-03-04 12:34 UTC, merged